CREATE DATABASE Grocery_Management;
USE Grocery_Management;

CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY auto_increment,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY auto_increment,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY auto_increment,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY auto_increment,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY auto_increment,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY auto_increment,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM CATEGORIES;
SELECT * FROM order_details;
SELECT * FROM customers;
select * from employees;
select * from orders;
select * from products;
select * from supplier;

-- Analysis Questions
-- Customer Insights
-- 1.How many unique customers have placed orders?
SELECT DISTINCT c.cust_name from customers c
INNER JOIN ORDERS O
ON C.CUST_ID = O.CUST_ID;

-- 2.Which customers have placed the highest number of orders?
SELECT 
    c.cust_id,
    c.cust_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o 
ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- 3. Total and average purchase value per customer
SELECT 
    c.cust_id,
    c.cust_name,
    SUM(od.total_price) AS total_purchase,
    AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o 
ON c.cust_id = o.cust_id
JOIN order_details od 
ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC;

-- 4. Top 5 customers by purchase amount
SELECT 
    c.cust_id, c.cust_name, SUM(od.total_price) AS total_spent
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id , c.cust_name
ORDER BY total_spent DESC
LIMIT 5;

-- Product Performance
-- 5. Number of products in each category
SELECT 
    cat.cat_name,
    COUNT(p.prod_id) AS total_products
FROM categories cat
LEFT JOIN products p 
ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;

-- 6. Average price of products by category
SELECT 
    cat.cat_name,
    ROUND(AVG(p.price),2) AS avg_price
FROM categories cat
JOIN products p 
ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;

-- 7. Products with highest sales volume
SELECT 
    p.prod_name,
    SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od 
ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_quantity_sold DESC;

-- 8. Total revenue generated by each product
SELECT 
    p.prod_name,
    SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od 
ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_revenue DESC;

-- 9. Product sales by category and supplier
SELECT 
    cat.cat_name,
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p 
ON od.prod_id = p.prod_id
JOIN categories cat 
ON p.cat_id = cat.cat_id
JOIN supplier s 
ON p.sup_id = s.sup_id
GROUP BY cat.cat_name, s.sup_name
ORDER BY total_revenue DESC;

-- Sales and Order Trends
-- 10. Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;

-- 11. Average value per order
SELECT 
    AVG(order_total) AS avg_order_value
FROM (
    SELECT 
        ord_id,
        SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS order_summary;

-- 12. Dates with highest number of orders
SELECT 
    order_date,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC;

-- 13. Monthly order trends
SELECT 
    MONTH(STR_TO_DATE(order_date,'%Y-%m-%d')) AS month,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY month
ORDER BY month;

-- Supplier Contribution
-- 14. Total number of suppliers
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- 15. Supplier providing most products
SELECT 
    s.sup_name,
    COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p 
ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY total_products DESC;

-- 16. Average price of products from each supplier
SELECT 
    s.sup_name,
    ROUND(AVG(p.price),2) AS avg_price
FROM supplier s
JOIN products p 
ON s.sup_id = p.sup_id
GROUP BY s.sup_name;

-- 17. Suppliers contributing most revenue
SELECT 
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p 
ON s.sup_id = p.sup_id
JOIN order_details od 
ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;

-- Employee Performance
-- 18. Employees who processed orders
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

-- 19. Employees handling most orders
SELECT 
    e.emp_name,
    COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o 
ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY total_orders DESC;

-- 20. Total sales processed by each employee
SELECT 
    e.emp_name,
    SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o 
ON e.emp_id = o.emp_id
JOIN order_details od 
ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY total_sales DESC;

-- Order Details Deep Dive
-- 21. Relationship between quantity and total price
SELECT 
    quantity,
    AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;

-- 22. Average quantity ordered per product
SELECT 
    p.prod_name,
    AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od 
ON p.prod_id = od.prod_id
GROUP BY p.prod_name;

-- 23. Unit price variation across products
SELECT 
    p.prod_name,
    MIN(od.each_price) AS min_price,
    MAX(od.each_price) AS max_price
FROM products p
JOIN order_details od 
ON p.prod_id = od.prod_id
GROUP BY p.prod_name;


